#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May  8 15:28:41 2025

@author: Jia Wei Teh

This script stores the default values for parameters
"""


default_parameters = {'model_name': 'example', 
                   'out_dir': 'def_dir', 
                   'verbose': 1.0, 
                   'output_format': 'JSON', 
                   'rand_input': 0.0, 
                   'log_mCloud': 6.0, 
                   'is_mCloud_beforeSF': 1.0, 
                   'sfe': 0.01, 
                   'nCore': 1e4, 
                   'rCore': 0.099, 
                   'metallicity': 1.0, 
                   'stochastic_sampling': 0.0, 
                   'n_trials': 1.0, 
                   'rand_log_mCloud': ['5', ' 7.47'], 
                   'rand_sfe': ['0.01', ' 0.10'], 
                   'rand_n_cloud': ['100.', ' 1000.'], 
                   'rand_metallicity': ['0.15', ' 1'], 
                   'mult_exp': 0.0, 
                   'r_coll': 1.0, 
                   'mult_SF': 1.0, 
                   'sfe_tff': 0.01, 
                   'imf': 'kroupa.imf', 
                   'stellar_tracks': 'geneva', 
                   'SB99_mass': 1e6,
                   'SB99_rotation': 1.0,
                   'SB99_BHCUT': 120.0,
                   'SB99_forcefile': 0.0,
                   'SB99_age_min': 500000.0,
                   'dens_profile': 'pL_prof', 
                   'dens_g_bE': 14.1, 
                   'dens_a_pL': 0, 
                   'dens_navg_pL': 100.0, 
                   'frag_enabled': 0.0, 
                   'frag_r_min': 0.1, 
                   'frag_grav': 0.0, 
                   'frag_grav_coeff': 0.67, 
                   'frag_RTinstab': 0.0, 
                   'frag_densInhom': 0.0, 
                   'frag_cf': 1.0, 
                   'frag_cf_end': 0.1,
                   'frag_enable_timescale': 1.0, 
                   'stop_n_diss': 1.0, 
                   'stop_t_diss': 1.0, 
                   'stop_r': 500.0, 
                   'stop_v': -10000.0,
                   'stop_t': 50, 
                   'stop_t_unit': 'Myr', 
                   'adiabaticOnlyInCore': False,
                   'immediate_leak': True,
                   'phase_Emin': 1e-4,
                   'write_main': 1.0, 
                   'write_stellar_prop': 0.0, 
                   'write_bubble': 0.0, 
                   'write_bubble_CLOUDY': 0.0, 
                   'write_shell': 0.0, 
                   'write_figures': 0.0,
                   'write_potential': 0.0,
                   'cooling_alpha': 0.6,
                   'cooling_beta': 0.8,
                   'cooling_delta': -0.17142857142857143,
                   'path_cooling_nonCIE': 'def_dir',
                   'path_cooling_CIE': 3,
                   'path_sps': 'def_dir',
                   'xi_Tb': 0.9,
                   'inc_grav': 1.0, 
                   'f_Mcold_wind': 0.0, 
                   'f_Mcold_SN': 0.0, 
                   'v_SN': 1000000000.0, 
                   'sigma0': 1.5e-21, 
                   'z_nodust': 0.05, 
                   'mu_n': 2.1287915392418182e-24, 
                   'mu_p': 1.0181176926808696e-24, 
                   't_ion': 10000.0, 
                   't_neu': 100.0, 
                   'nISM': 10, 
                   'kappa_IR': 4.0, 
                   'gamma_adia': 1.6666666666666667, 
                   'thermcoeff_wind': 1.0, 
                   'thermcoeff_SN': 1.0,
                   'alpha_B': 2.59e-13,
                   'gamma_mag': 1.3333333333333333,
                   'log_BMW': -4.3125,
                   'log_nMW': 2.065,
                   'c_therm': 1.2e-6,
                   'dMdt_factor': 1.646,
                   'T_r2Prime': 3e4
                   }

