#!/usr/bin/env python3
"""Generate MANIFEST.md — the which-version-is-this ledger for every committed artifact.

Answers "is this CSV/figure the current one, or a leftover from several versions ago?"
with git facts, not memory:

  * last-updated date + commit (git log -1 --follow) per artifact;
  * the producing script (best-effort: the committed .py that names the artifact);
  * a ⚠️ STALE-RISK flag when the PRODUCER changed more recently than the artifact —
    i.e. the committed output may not reflect the current builder;
  * UNTRACKED for files present on disk but not in git (never quotable).

Recency is orthogonal to QUOTABILITY — a file can be current *and* contaminated.
Quotability lives in CONTAMINATION.md; read both.

Regenerate (and commit the result IN THE SAME COMMIT as any new/updated artifact):
    python docs/dev/transition/pdv-trigger/make_manifest.py
"""

import os
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
EXTS = {".csv", ".png", ".txt", ".html", ".sbatch", ".param"}


def git(*args):
    return subprocess.run(
        ["git", "-C", str(REPO), *args], capture_output=True, text=True
    ).stdout.strip()


def last_commit(relpath):
    out = git("log", "-1", "--follow", "--format=%as %h", "--", relpath)
    return out.split() if out else (None, None)


def main():
    tracked = set(git("ls-files", "--", str(HERE.relative_to(REPO))).splitlines())

    artifacts, scripts = [], []
    for p in sorted(HERE.rglob("*")):
        if not p.is_file() or p.name.startswith("."):
            continue
        rel = str(p.relative_to(REPO))
        if p.suffix == ".py":
            scripts.append(rel)
        elif p.suffix in EXTS:
            artifacts.append(rel)

    # producer = the workstream's naming convention make_/harvest_/reduce_<stem>.py -> <stem>*.
    # Scripts that merely MENTION an artifact (report builders, readers) are listed as refs and
    # excluded from staleness — otherwise every consumer edit would false-alarm every input.
    script_text = {s: (REPO / s).read_text(errors="ignore") for s in scripts if s in tracked}
    script_date = {s: last_commit(s) for s in script_text}

    def stem(script):
        name = os.path.basename(script)[:-3]
        for pre in ("make_", "harvest_", "reduce_", "_"):
            if name.startswith(pre) and len(name) > len(pre):
                name = name[len(pre) :]
        return name

    def embedded_stamp(relpath):
        """First-line '# generated ...' provenance stamp (_stamp.py), if the artifact has one."""
        if not relpath.endswith((".csv", ".txt")):
            return None
        try:
            with open(REPO / relpath, errors="ignore") as fh:
                first = fh.readline()
        except OSError:
            return None
        if first.startswith("# generated "):
            return first[2:].strip()
        return None

    rows = []
    n_stale = n_untracked = n_stamped = 0
    for a in artifacts:
        base = os.path.basename(a)
        if a not in tracked:
            rows.append((None, base, a, "—", "🚫 UNTRACKED (not in git — never quote)"))
            n_untracked += 1
            continue
        date, sha = last_commit(a)
        mentions = [s for s, t in script_text.items() if base in t and s != a]
        producers = [s for s in mentions if len(stem(s)) >= 4 and base.startswith(stem(s))]
        refs = [s for s in mentions if s not in producers]
        if producers:
            prod_txt = "by " + ", ".join(f"`{os.path.basename(s)}`" for s in producers[:2])
        elif refs:
            prod_txt = "producer unknown (HPC/hand-made); refs: " + ", ".join(
                f"`{os.path.basename(s)}`" for s in refs[:2]
            )
        else:
            prod_txt = "— (hand-made/HPC, unreferenced)"
        stale = ""
        newer = [s for s in producers if script_date[s][0] and date and script_date[s][0] > date]
        if newer:
            n_stale += 1
            stale = (
                "⚠️ STALE-RISK: builder newer ("
                + ", ".join(f"{os.path.basename(s)} {script_date[s][0]}" for s in newer[:2])
                + ") — regenerate or justify"
            )
        st = embedded_stamp(a)
        if st:
            n_stamped += 1
            prod_txt += f" · 🕐 {st}"
        rows.append(
            (date, base, a, f"{date} `{sha}`", prod_txt + ((" · " + stale) if stale else ""))
        )

    rows.sort(key=lambda r: (r[0] or "0000"), reverse=True)

    out = [
        "# MANIFEST — artifact versions (generated, do not hand-edit)",
        "",
        "> Generated by `make_manifest.py` from git history — regenerate it in the same commit as",
        "> any artifact change. **Newest first.** Recency ≠ quotability: check `CONTAMINATION.md`",
        "> before quoting any number. ⚠️ STALE-RISK = the producing script changed after the",
        "> artifact was last regenerated (the committed output may be from an older builder).",
        ">",
        "> **Commit dates are UPPER BOUNDS** — work is often bulk-committed days after it was",
        "> produced. Artifacts carrying a 🕐 first-line provenance stamp (`_stamp.py`: true UTC",
        "> generation time + builder + code commit, `+dirty` = made from an uncommitted tree)",
        "> are exact; stamp-less artifacts predate the convention (2026-07-02) — for those, only",
        "> the commit date is known. **Every new/edited builder must write the stamp.**",
        "",
        f"{len(rows)} artifacts · {n_stale} stale-risk · {n_untracked} untracked · {n_stamped} stamped 🕐",
        "",
        "| last updated (commit) | artifact | producer / flags |",
        "|---|---|---|",
    ]
    for _, base, rel, when, info in rows:
        sub = os.path.dirname(os.path.relpath(rel, str(HERE.relative_to(REPO))))
        loc = f"{sub}/" if sub else ""
        out.append(f"| {when} | `{loc}{base}` | {info} |")

    (HERE / "MANIFEST.md").write_text("\n".join(out) + "\n")
    print(
        f"wrote MANIFEST.md: {len(rows)} artifacts, {n_stale} stale-risk, {n_untracked} untracked"
    )


if __name__ == "__main__":
    main()
