#!/usr/bin/env python3
"""Why `P_HII / P_confining == 1.0000000000` — and why it is *not* bit-identical.

Three independent workstreams measured the same ratio and each reported it as a
near-but-not-exact identity (see `docs/dev/phii-identity/README.md`):

    weak-winds      Pb / P_HII    = 1.0000000000  (10 digits, implicit phase)
    switchon-succ.  P_HII / Pb    = 1.0000        (4 digits, energy phase)
    momentum-pdrive P_HII vs P_ram, max relΔ 2.8e-16 / 3.4e-16 / 3.6e-16,
                    bit-identical on only 6/30, 35/95, 38/104 rows

`momentum-pdrive/README.md` §2 treats the missing bit-identity as evidence that
`P_HII` is *computed* by some path that happens to be algebraically equivalent,
and leaves the mechanism inferred-but-unmeasured. This harness closes that: the
non-identity is nothing but the float round-trip through the same three factors,
and it predicts both the ~1-2 ULP spread *and* the ~36% bit-equal rate.

The round trip, verbatim from current source (@ 731ac50):

    shell_structure.py:124-126   nShell0 = (mu_ion_shell / mu_convert /
                                            (k_B * TShell_ion)) * Pb
    shell_structure.py:251       n_IF_Str = min(n_IF_Str, shell_n0)
    run_momentum_phase.py:634    P_HII = (mu_convert / mu_ion_shell) * n_IF_Str
                                         * k_B * TShell_ion

When the cap binds, `n_IF_Str := shell_n0` and the second line undoes the first
*exactly in exact arithmetic* — so `P_HII === Pb` is an algebraic identity, not a
numerical coincidence, and it carries no information about the ionizing field.
In float it is an identity only up to the rounding of a multiply/divide round
trip, because (a) `mu_ion_shell/mu_convert` and `mu_convert/mu_ion_shell` are
each rounded separately and are not exact reciprocals, and (b) the two sides
associate `k_B * TShell_ion` differently.

Usage (from the repo root):
    python docs/dev/phii-identity/harness/roundtrip_ulp.py

Writes docs/dev/phii-identity/data/roundtrip_ulp.csv. Pure arithmetic — no
simulation, runs in under a second, needs no run dirs.
"""

import csv
import random
from pathlib import Path

from trinity._functions import unit_conversions as cvt

OUT_CSV = Path(__file__).resolve().parents[1] / "data" / "roundtrip_ulp.csv"

# Production constants, as read_param derives them (registry.py:389-405, 442):
#   mu_convert   = 1 + 4*x_He                       @ x_He=0.1
#   mu_ion_shell = mu_convert / (2 + x_He*(1+Z_He_shell))  @ Z_He_shell=1
X_HE, Z_HE_SHELL = 0.1, 1
MU_CONVERT = 1.0 + 4.0 * X_HE
MU_ION_SHELL = MU_CONVERT / (2.0 + X_HE * (1.0 + Z_HE_SHELL))
T_SHELL_ION = 1e4
K_B_CGS = 1.380649e-16
K_B_AU = K_B_CGS * cvt.k_B_cgs2au  # internal (astro) units — what the solver uses

N_DRAWS = 100_000
# Pb spans ~12 dex across a run: 3.2e9 (t=0) down to 5.5e0 (15 Myr) in
# weak-winds FINDINGS; the momentum-phase P_ram range is 1.9x-88x per run.
PB_LO_DEX, PB_HI_DEX = 0.0, 12.0


def round_trip(Pb, k_B):
    """One cap-bound P_HII evaluation, in the solver's operation order."""
    # shell_structure.py:124-126
    n_shell0 = MU_ION_SHELL / MU_CONVERT / (k_B * T_SHELL_ION) * Pb
    # shell_structure.py:251 — the cap binds, so n_IF_Str is exactly shell_n0
    n_IF_Str = n_shell0
    # run_momentum_phase.py:634 (identical expression at run_transition_phase.py:564,
    # run_energy_phase.py:225)
    return (MU_CONVERT / MU_ION_SHELL) * n_IF_Str * k_B * T_SHELL_ION


def sweep(k_B, label, seed=0):
    rng = random.Random(seed)
    worst = 0.0
    n_bit = 0
    for _ in range(N_DRAWS):
        Pb = 10.0 ** rng.uniform(PB_LO_DEX, PB_HI_DEX)
        P_HII = round_trip(Pb, k_B)
        if P_HII == Pb:
            n_bit += 1
        worst = max(worst, abs(P_HII - Pb) / Pb)
    return {
        "units": label,
        "k_B": f"{k_B:.6e}",
        "n_draws": N_DRAWS,
        "Pb_range_dex": f"{PB_LO_DEX:g}-{PB_HI_DEX:g}",
        "max_abs_rel_diff": f"{worst:.3g}",
        "max_diff_in_ulp": f"{worst / 2.0**-52:.2f}",
        "n_bitequal": n_bit,
        "frac_bitequal": f"{n_bit / N_DRAWS:.3f}",
    }


def main():
    rows = [sweep(K_B_AU, "astro (internal)"), sweep(K_B_CGS, "cgs")]
    w = max(len(r["units"]) for r in rows)
    print(f"{'units':{w}}  {'max relΔ':>10} {'ULP':>6} {'bit-equal':>10}")
    for r in rows:
        print(
            f"{r['units']:{w}}  {r['max_abs_rel_diff']:>10} {r['max_diff_in_ulp']:>6} "
            f"{r['frac_bitequal']:>10}"
        )
    print(
        "\nMeasured in production runs (momentum-pdrive/data/phii_pram_evidence.csv):"
        "\n  max relΔ 2.82e-16 / 3.42e-16 / 3.64e-16;  bit-equal 6/30=0.200,"
        " 35/95=0.368, 38/104=0.365"
    )
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="") as fh:
        fh.write("# generated by docs/dev/phii-identity/harness/roundtrip_ulp.py\n")
        fh.write("# command: python docs/dev/phii-identity/harness/roundtrip_ulp.py\n")
        fh.write(
            "# Pure arithmetic model of the cap-bound P_HII round trip (no simulation).\n"
            "# Reproduces the ULP spread and bit-equal fraction measured in production,\n"
            "# confirming P_HII === P_confining is an algebraic identity, not a coincidence.\n"
        )
        wr = csv.DictWriter(fh, fieldnames=list(rows[0]))
        wr.writeheader()
        wr.writerows(rows)
    print(f"\nwrote {OUT_CSV}")


if __name__ == "__main__":
    main()
