#!/usr/bin/env python3
"""GATE G3: the energy-driven similarity slope dlnR/dlnt.

Weaver+77 energy-driven expansion into a uniform medium with constant mechanical
luminosity gives R ~ t^(3/5), i.e. dlnR/dlnt = 0.600. A dropped or mis-scaled
driving term shows up as a wrong slope regardless of what the code says about
itself, so this is the asymptotic check of PLAN.md §4 G3.

Reads only committed CSVs (no runs) and writes data/g3_slopes.csv. The control
is the GMC config, which sets densPL_alpha=0 — the uniform medium the 3/5 law
assumes. Usage:

    python docs/dev/phase1a-init/harness/g3_slopes.py

Caveat worth keeping in mind when reading the output: the measured late-time
slope is ~0.58, not exactly 0.600, because TRINITY's mechanical luminosity is
not constant (it follows the SB99 tables) and gravity, cooling and P_HII all
contribute. The load-bearing comparison is therefore stock vs fixed — BOTH
settle on the same ~0.58, so the fix does not move the asymptote; it only
changes how fast the trajectory gets there.
"""
import csv
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

# (label, committed CSV stem). Both are the uniform-density GMC control.
ARMS = [("production_fix", "g2_gmc_prod"), ("stock_prefix", "gmc_control")]

WINDOWS = [
    (1e-6, 1e-4, "t<100yr_relaxation"),
    (1e-4, 1e-3, "0.1-1kyr"),
    (1e-3, 1e-2, "1-10kyr"),
    (1e-2, 1e-1, "10-100kyr"),
]


def load(stem):
    path = os.path.join(DATA, f"{stem}.csv")
    with open(path) as fh:
        rows = list(csv.DictReader(l for l in fh if not l.startswith("#")))
    return [(float(r["t_now"]), float(r["R2"])) for r in rows]


def local_slopes(series):
    """Centred difference of ln R against ln t — the local similarity exponent."""
    out = []
    for i in range(1, len(series) - 1):
        (t0, r0), (t1, _), (t2, r2) = series[i - 1], series[i], series[i + 1]
        if min(t0, r0, t2, r2) <= 0 or t2 == t0:
            continue
        out.append((t1, (math.log(r2) - math.log(r0)) / (math.log(t2) - math.log(t0))))
    return out


def main():
    out_path = os.path.join(DATA, "g3_slopes.csv")
    with open(out_path, "w", newline="") as fh:
        fh.write("# GATE G3: local energy-driven similarity slope dlnR/dlnt vs the Weaver 3/5 law.\n")
        fh.write("# Generated by harness/g3_slopes.py from committed CSVs; uniform-density GMC\n")
        fh.write("# control (densPL_alpha=0). production_fix=a944727, stock_prefix=pre-fix baseline.\n")
        w = csv.writer(fh)
        w.writerow(["arm", "window", "n_points", "mean_slope", "last_slope", "weaver_3_5", "abs_diff_vs_3_5"])
        for label, stem in ARMS:
            slopes = local_slopes(load(stem))
            for lo, hi, name in WINDOWS:
                vals = [s for t, s in slopes if lo <= t <= hi]
                if not vals:
                    continue
                mean = sum(vals) / len(vals)
                w.writerow([label, name, len(vals), f"{mean:.4f}", f"{vals[-1]:.4f}",
                            "0.6000", f"{abs(mean - 0.6):.4f}"])
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
